M48
; DRILL file {KiCad (6.0.0)} date Sun Mar 13 20:46:11 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-03-13T20:46:11-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.550
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X54.515Y-2.115
X58.515Y-2.115
T2
X2.54Y0.0
X2.54Y-52.705
X70.485Y0.0
X70.485Y-52.705
T0
M30
