M48
; DRILL file {KiCad (6.0.0)} date Tue Jan  4 00:39:00 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-01-04T00:39:00-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.400
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X179.577Y-51.975
X179.577Y-85.075
T2
X129.794Y-48.514
X129.794Y-87.376
X182.626Y-48.514
X182.626Y-87.376
T0
M30
