M48
; DRILL file {KiCad (6.0.0)} date Tue Jan  4 00:37:32 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-01-04T00:37:32-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X108.204Y-90.678
X108.204Y-122.682
X190.754Y-90.678
X190.754Y-122.682
T0
M30
