M48
; DRILL file {KiCad (6.0.0)} date Sun Oct  9 23:31:43 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-10-09T23:31:43-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X21.462Y-123.291
X21.462Y-166.37
X137.541Y-123.291
X137.541Y-166.37
T0
M30
