M48
; DRILL file {KiCad (6.0.0)} date Sun Mar 13 18:43:23 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-03-13T18:43:23-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X93.345Y-40.64
X93.345Y-76.2
X136.525Y-40.64
X136.525Y-76.2
T0
M30
