M48
; DRILL file {KiCad (6.0.0)} date Tue Dec 27 21:52:25 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-12-27T21:52:25-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X120.816Y-94.121
X120.816Y-137.2
X236.895Y-94.121
X236.895Y-137.2
T0
M30
