M48
; DRILL file {KiCad (6.0.0)} date Sun Oct  9 23:28:57 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-10-09T23:28:57-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X94.4Y-83.834
X94.4Y-126.913
X210.479Y-83.834
X210.479Y-126.913
T0
M30
